window.jest_html_reporters_callback__({"numFailedTestSuites":0,"numFailedTests":0,"numPassedTestSuites":8,"numPassedTests":20,"numPendingTestSuites":0,"numPendingTests":0,"numRuntimeErrorTestSuites":0,"numTodoTests":0,"numTotalTestSuites":8,"numTotalTests":20,"startTime":1654627817792,"success":false,"testResults":[{"leaks":false,"numFailingTests":0,"numPassingTests":3,"numPendingTests":0,"numTodoTests":0,"perfStats":{"end":1654627821293,"runtime":2878,"slow":false,"start":1654627818415},"skipped":false,"testFilePath":"C:\\Users\\sacha\\OneDrive\\Documents\\GitHub\\dyal\\tests\\commandBus.test.ts","testResults":[{"ancestorTitles":["CommandBus","Given a command Bus with 3 command handlers registered","When I use the command bus middleware to execute a command "],"duration":5,"failureDetails":[],"failureMessages":[],"fullName":"CommandBus Given a command Bus with 3 command handlers registered When I use the command bus middleware to execute a command  Then the correct handler is called And the Next callback is not called","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then the correct handler is called And the Next callback is not called"},{"ancestorTitles":["CommandBus","Given a command Bus with 3 command handlers registered","When I use the command bus middleware to execute a query "],"duration":2,"failureDetails":[],"failureMessages":[],"fullName":"CommandBus Given a command Bus with 3 command handlers registered When I use the command bus middleware to execute a query  Then the next callback is called directly","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then the next callback is called directly"},{"ancestorTitles":["CommandBus","Given a command Bus with 3 command handlers registered","When I use the command bus middleware to execute an unregistered command "],"duration":1,"failureDetails":[],"failureMessages":[],"fullName":"CommandBus Given a command Bus with 3 command handlers registered When I use the command bus middleware to execute an unregistered command  Then an error is thrown","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then an error is thrown"}],"failureMessage":null},{"leaks":false,"numFailingTests":0,"numPassingTests":1,"numPendingTests":0,"numTodoTests":0,"perfStats":{"end":1654627821404,"runtime":2986,"slow":false,"start":1654627818418},"skipped":false,"testFilePath":"C:\\Users\\sacha\\OneDrive\\Documents\\GitHub\\dyal\\tests\\createApp.test.ts","testResults":[{"ancestorTitles":["createApp()","Given I create an app","With no dependency"],"duration":8,"failureDetails":[],"failureMessages":[],"fullName":"createApp() Given I create an app With no dependency Then it returns an app","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it returns an app"}],"failureMessage":null},{"leaks":false,"numFailingTests":0,"numPassingTests":2,"numPendingTests":0,"numTodoTests":0,"perfStats":{"end":1654627821419,"runtime":3012,"slow":false,"start":1654627818407},"skipped":false,"testFilePath":"C:\\Users\\sacha\\OneDrive\\Documents\\GitHub\\dyal\\tests\\executeCommand.test.ts","testResults":[{"ancestorTitles":["app.execute()","Given an app","With a command bus that register multiple commands","When I execute a CommandB command"],"duration":5,"failureDetails":[],"failureMessages":[],"fullName":"app.execute() Given an app With a command bus that register multiple commands When I execute a CommandB command Then it should call CommandB handler","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it should call CommandB handler"},{"ancestorTitles":["app.execute()","Given an app","With a command bus that register multiple commands","When I execute an UnknownCommand"],"duration":2,"failureDetails":[],"failureMessages":[],"fullName":"app.execute() Given an app With a command bus that register multiple commands When I execute an UnknownCommand Then it should throw an error","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it should throw an error"}],"failureMessage":null},{"leaks":false,"numFailingTests":0,"numPassingTests":4,"numPendingTests":0,"numTodoTests":0,"perfStats":{"end":1654627821430,"runtime":3007,"slow":false,"start":1654627818423},"skipped":false,"testFilePath":"C:\\Users\\sacha\\OneDrive\\Documents\\GitHub\\dyal\\tests\\execute.test.ts","testResults":[{"ancestorTitles":["app.execute()","Given an app","With multiple middlewares","When I execute a tests command"],"duration":4,"failureDetails":[],"failureMessages":[],"fullName":"app.execute() Given an app With multiple middlewares When I execute a tests command Then it should call middlewares in order and then backward","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it should call middlewares in order and then backward"},{"ancestorTitles":["app.execute()","Given an app","With multiple middleware","When I execute a tests command","And one middleware throws"],"duration":1,"failureDetails":[],"failureMessages":[],"fullName":"app.execute() Given an app With multiple middleware When I execute a tests command And one middleware throws Then it should throw and stop the middlewares execution","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it should throw and stop the middlewares execution"},{"ancestorTitles":["app.execute()","Given an app","With multiple middleware","When a middleware calls next twice"],"duration":0,"failureDetails":[],"failureMessages":[],"fullName":"app.execute() Given an app With multiple middleware When a middleware calls next twice Then it should throw","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it should throw"},{"ancestorTitles":["app.execute()","Given an app","With no middelwares","When I execute a test command"],"duration":0,"failureDetails":[],"failureMessages":[],"fullName":"app.execute() Given an app With no middelwares When I execute a test command Then it throw an error","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it throw an error"}],"failureMessage":null},{"leaks":false,"numFailingTests":0,"numPassingTests":3,"numPendingTests":0,"numTodoTests":0,"perfStats":{"end":1654627821441,"runtime":2998,"slow":false,"start":1654627818443},"skipped":false,"testFilePath":"C:\\Users\\sacha\\OneDrive\\Documents\\GitHub\\dyal\\tests\\queryBus.test.ts","testResults":[{"ancestorTitles":["QueryBus","Given a query Bus with 3 query handlers registered","When I use the query bus middleware to execute a query "],"duration":5,"failureDetails":[],"failureMessages":[],"fullName":"QueryBus Given a query Bus with 3 query handlers registered When I use the query bus middleware to execute a query  Then the correct handler is called And the Next callback is not called","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then the correct handler is called And the Next callback is not called"},{"ancestorTitles":["QueryBus","Given a query Bus with 3 query handlers registered","When I use the query bus middleware to execute a command "],"duration":1,"failureDetails":[],"failureMessages":[],"fullName":"QueryBus Given a query Bus with 3 query handlers registered When I use the query bus middleware to execute a command  Then the next callback is called directly","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then the next callback is called directly"},{"ancestorTitles":["QueryBus","Given a query Bus with 3 query handlers registered","When I use the query bus middleware to execute an unregistered query "],"duration":0,"failureDetails":[],"failureMessages":[],"fullName":"QueryBus Given a query Bus with 3 query handlers registered When I use the query bus middleware to execute an unregistered query  Then an error is thrown","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then an error is thrown"}],"failureMessage":null},{"leaks":false,"numFailingTests":0,"numPassingTests":2,"numPendingTests":0,"numTodoTests":0,"perfStats":{"end":1654627821450,"runtime":3045,"slow":false,"start":1654627818405},"skipped":false,"testFilePath":"C:\\Users\\sacha\\OneDrive\\Documents\\GitHub\\dyal\\tests\\executeQuery.test.ts","testResults":[{"ancestorTitles":["app.execute()","Given an app","With a Query bus that register multiple Queries","When I execute a QueryB Query"],"duration":6,"failureDetails":[],"failureMessages":[],"fullName":"app.execute() Given an app With a Query bus that register multiple Queries When I execute a QueryB Query Then it should call QueryB handler","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it should call QueryB handler"},{"ancestorTitles":["app.execute()","Given an app","With a Query bus that register multiple Queries","When I execute an UnknownQuery"],"duration":1,"failureDetails":[],"failureMessages":[],"fullName":"app.execute() Given an app With a Query bus that register multiple Queries When I execute an UnknownQuery Then it should throw an error","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it should throw an error"}],"failureMessage":null},{"leaks":false,"numFailingTests":0,"numPassingTests":3,"numPendingTests":0,"numTodoTests":0,"perfStats":{"end":1654627821460,"runtime":3037,"slow":false,"start":1654627818423},"skipped":false,"testFilePath":"C:\\Users\\sacha\\OneDrive\\Documents\\GitHub\\dyal\\tests\\composeMiddlewares.test.ts","testResults":[{"ancestorTitles":["composeMiddlewares()","Given an empty array of middlwares","When I compose them"],"duration":1,"failureDetails":[],"failureMessages":[],"fullName":"composeMiddlewares() Given an empty array of middlwares When I compose them Then it does not throws","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it does not throws"},{"ancestorTitles":["composeMiddlewares()","Given an empty array of invalid middlewares","When I compose them"],"duration":2,"failureDetails":[],"failureMessages":[],"fullName":"composeMiddlewares() Given an empty array of invalid middlewares When I compose them Then it throws","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it throws"},{"ancestorTitles":["composeMiddlewares()","Given an invalid middlewares","When I compose them"],"duration":1,"failureDetails":[],"failureMessages":[],"fullName":"composeMiddlewares() Given an invalid middlewares When I compose them Then it throws","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it throws"}],"failureMessage":null},{"leaks":false,"numFailingTests":0,"numPassingTests":2,"numPendingTests":0,"numTodoTests":0,"perfStats":{"end":1654627821483,"runtime":3064,"slow":false,"start":1654627818419},"skipped":false,"testFilePath":"C:\\Users\\sacha\\OneDrive\\Documents\\GitHub\\dyal\\tests\\use.test.ts","testResults":[{"ancestorTitles":["app.use()","Given I an app","With no dependency","When I use a middleware"],"duration":0,"failureDetails":[],"failureMessages":[],"fullName":"app.use() Given I an app With no dependency When I use a middleware Then it should not throw","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it should not throw"},{"ancestorTitles":["app.use()","Given I an app","With no dependency","When I try use a middleware that is not a function"],"duration":8,"failureDetails":[],"failureMessages":[],"fullName":"app.use() Given I an app With no dependency When I try use a middleware that is not a function Then it should throw","invocations":1,"location":null,"numPassingAsserts":0,"status":"passed","title":"Then it should throw"}],"failureMessage":null}],"wasInterrupted":false,"config":{"bail":0,"changedFilesWithAncestor":false,"collectCoverage":true,"collectCoverageFrom":["src/**/*.ts"],"coverageDirectory":"C:\\Users\\sacha\\OneDrive\\Documents\\GitHub\\dyal\\docs\\jest","coverageProvider":"babel","coverageReporters":["lcov","text-summary"],"detectLeaks":false,"detectOpenHandles":false,"errorOnDeprecated":false,"expand":false,"findRelatedTests":false,"forceExit":false,"json":false,"lastCommit":false,"listTests":false,"logHeapUsage":false,"maxConcurrency":5,"maxWorkers":11,"noStackTrace":false,"nonFlagArgs":[],"notify":false,"notifyMode":"failure-change","onlyChanged":false,"onlyFailures":false,"passWithNoTests":false,"projects":[],"reporters":[["default",{}],["C:\\Users\\sacha\\OneDrive\\Documents\\GitHub\\dyal\\node_modules\\jest-html-reporters\\index.js",{"publicPath":"./docs/test-report","filename":"index.html","openReport":true,"pageTitle":"Dyal tests report"}]],"rootDir":"C:\\Users\\sacha\\OneDrive\\Documents\\GitHub\\dyal","runTestsByPath":false,"skipFilter":false,"testFailureExitCode":1,"testPathPattern":"","testSequencer":"C:\\Users\\sacha\\OneDrive\\Documents\\GitHub\\dyal\\node_modules\\@jest\\test-sequencer\\build\\index.js","updateSnapshot":"new","useStderr":false,"watch":false,"watchAll":false,"watchman":true,"coverageLinkPath":"..\\jest\\lcov-report\\index.html"},"endTime":1654627821595,"_reporterOptions":{"publicPath":"./docs/test-report","filename":"index.html","expand":false,"pageTitle":"Dyal tests report","hideIcon":false,"testCommand":"npx jest","openReport":true,"failureMessageOnly":false,"enableMergeData":false,"dataMergeLevel":1,"inlineSource":false},"attachInfos":{}})